language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-3.3.0-20160817231550-75d3c9c.tar.gz | tar xz
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; + test; + package; scripted'
  && ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local core generator
  && ci/sbt-ci-deploy.sh ivy http://commbank.artifactoryonline.com/commbank ext-releases-local-ivy plugin
  && ci/sbt-ci-build-doc.sh https://commbank.github.io/ https://github.com/CommBank/humbug/
  && ci/ci-push-branch.sh gh-pages
after_script:
- rm -rf ci
- find $HOME/.ivy2 -name "*humbug*" -delete
env:
  global:
  - secure: bCV/fYFXFvTgk2zNV4LA7N2y2Y8EInxwsdq0mUp2LbAy9z94NofZu309YAJSAab2wge/gBejxbQgRSloZVSKAbLfal4LaJshx1koNXPuozKoHOs53MicY4Vfv+8v++B0bd238EbjhJCdcVrQZ/QcSTqRqIc7Z3MI2WAxpz2w16I=
  - secure: hxDt95vWpTFyqkg0JSeJm55YPWIIWM9/KbJUPZJhNpKRy9z6eVfnNoC/IJ/T07QdgovA9J6W+ZqbDvijMXIlFRMEBQCtYgD9GPbBqV0/Fvv6NE6y3adkGTJBDvA+2kYZnSbnu3Ner993duoC+CqVh2kyYEs8eYEi5qXDAncpLLY=
before_install:
- openssl aes-256-cbc -K $encrypted_c3852da82fb3_key -iv $encrypted_c3852da82fb3_iv
  -in .ci/deploy-key.enc -out .ci/deploy-key.pem -d
