language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; + test; + package; scripted' && ci/sbt-deploy.sh
  core generator && ci/sbt-deploy-ivy.sh plugin && ci/sbt-gh-pages-ssh.sh
after_script:
- rm -rf ci
- find $HOME/.ivy2 -name "*humbug*" -delete
env:
  global:
    secure: ON4AVI3xRnRd9a+SHOvcYiUWlKqn/x9cKNdtj2Ku/AglJWwyUaGi8rfrVWUM3EOlvh+0Rffg3zgSYkkiPXnr6J0SjZeKyre9x/izeeafUmcOVD4grOqKhUKp9JlmN44f6jMBE7xMh142AphhAJ3i/4v3Y33VJ1BnbfofkxmkSoA=
before_install:
- openssl aes-256-cbc -K $encrypted_c3852da82fb3_key -iv $encrypted_c3852da82fb3_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key.pem -d
